version: '{build}'
image: 'Visual Studio 2017'
platform: x64

clone_folder: 'c:\go\src\github.com\mavimo\drone-chromewebstore'
max_jobs: 1

environment:
  GOPATH: c:\go
  docker_username:
    secure: 97GbkX38qb+tyKeuFpReng==
  docker_password:
    secure: oTzFQABMj0Db/AcPtBCRQA==

branches:
  only:
    - master

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - docker version
  - curl -fsS -o c:\go\bin\dep.exe https://github.com/golang/dep/releases/download/v0.4.1/dep-windows-amd64.exe
  - dep.exe ensure

build_script:
  - ps: |
      if ( $env:APPVEYOR_REPO_TAG -eq 'false' ) {
        go build -ldflags "-X main.Version=$env:APPVEYOR_REPO_COMMIT -X main.BuildNum=$env:APPVEYOR_BUILD_VERSION" -a -o drone-chromewebstore.exe
      } else {
        $version = $env:APPVEYOR_REPO_TAG_NAME
        go build -ldflags "-X main.Version=$version -X main.BuildNum=$env:APPVEYOR_BUILD_VERSION" -a -o drone-chromewebstore.exe
      }
      dir
      docker pull microsoft/nanoserver:10.0.14393.1884
      docker build -f Dockerfile.windows -t mavimo/drone-chromewebstore:windows-amd64 .

test_script:
  - ps: |
      docker run --rm mavimo/drone-chromewebstore:windows-amd64 --version

deploy_script:
  - ps: |
      if ( $env:APPVEYOR_PULL_REQUEST_NUMBER ) {
        Write-Host Nothing to deploy.
      } else {
        docker login --username $env:DOCKER_USERNAME --password $env:DOCKER_PASSWORD
        if ( $env:APPVEYOR_REPO_TAG -eq 'true' ) {
          $major,$minor,$patch = $env:APPVEYOR_REPO_TAG_NAME.split('.')
          docker push mavimo/drone-chromewebstore:windows-amd64
          docker tag mavimo/drone-chromewebstore:windows-amd64 mavimo/drone-chromewebstore:$major.$minor.$patch-windows-amd64
          docker push mavimo/drone-chromewebstore:$major.$minor.$patch-windows-amd64
          docker tag mavimo/drone-chromewebstore:windows-amd64 mavimo/drone-chromewebstore:$major.$minor-windows-amd64
          docker push mavimo/drone-chromewebstore:$major.$minor-windows-amd64
          docker tag mavimo/drone-chromewebstore:windows-amd64 mavimo/drone-chromewebstore:$major-windows-amd64
          docker push mavimo/drone-chromewebstore:$major-windows-amd64
        } else {
          if ( $env:APPVEYOR_REPO_BRANCH -eq 'master' ) {
            docker push mavimo/drone-chromewebstore:windows-amd64
          }
        }
      }
